\c geoserver
CREATE SCHEMA IF NOT EXISTS acl;
CREATE SCHEMA IF NOT EXISTS pgconfig;
CREATE SCHEMA IF NOT EXISTS jdbcconfig;
CREATE EXTENSION IF NOT EXISTS postgis;

-- works as "CREATE DATBASE IF NOT EXISTS"
SELECT 'CREATE DATABASE postgis' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'postgis')\gexec

\c postgis
CREATE EXTENSION IF NOT EXISTS postgis;

-- works as "CREATE DATBASE IF NOT EXISTS"
SELECT 'CREATE DATABASE acceptance' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'acceptance')\gexec

\c acceptance
CREATE SCHEMA IF NOT EXISTS test1;
CREATE SCHEMA IF NOT EXISTS test2;
CREATE EXTENSION IF NOT EXISTS postgis;
