services:
  jre:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/gs-cloud-base-jre:${TAG}
    build:
      pull: true
      context: ../src/apps/base-images/jre/

  spring-boot:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/gs-cloud-base-spring-boot:${TAG}
    build:
      context: ../src/apps/base-images/spring-boot/

  spring-boot3:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/gs-cloud-base-spring-boot3:${TAG}
    build:
      context: ../src/apps/base-images/spring-boot3/

  geoserver-common:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/gs-cloud-base-geoserver-image:${TAG}
    build:
      context: ../src/apps/base-images/geoserver/
