services:
  wfs:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-wfs:${TAG}
    build:
      context: ../src/apps/geoserver/wfs/

  wms:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-wms:${TAG}
    build:
      context: ../src/apps/geoserver/wms/

  wcs:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-wcs:${TAG}
    build:
      context: ../src/apps/geoserver/wcs/

  wps:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-wps:${TAG}
    build:
      context: ../src/apps/geoserver/wps/

  restconfig:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-rest:${TAG}
    build:
      context: ../src/apps/geoserver/restconfig/

  webui:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-webui:${TAG}
    build:
      context: ../src/apps/geoserver/webui/

  gwc:
    extends:
      file: templates.yml
      service: current-platform
    image: ${REPOSITORY}/geoserver-cloud-gwc:${TAG}
    build:
      context: ../src/apps/geoserver/gwc/

    
