services:
  discovery:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-discovery:${TAG}
    build:
      context: ../src/apps/infrastructure/discovery/

  config:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-config:${TAG}
    build:
      context: ../src/apps/infrastructure/config/

  gateway:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-gateway:${TAG}
    build:
      context: ../src/apps/infrastructure/gateway/
