services:
  geodatabase:
    image: imresamu/postgis:15-3.4
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: geodata
      POSTGRES_PASSWORD: geodata
    restart: always
    volumes:
      - ./acceptance_pg_entrypoint:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"  # Expose on port 5433 to avoid conflict with local PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geodata"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  acceptance:
    image: geoservercloud/acceptance:latest
    user: ${GS_USER}
    depends_on:
      geodatabase:
        condition: service_healthy
      postgis:
        condition: service_healthy
      gateway:
        condition: service_healthy
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy
      acl:
        condition: service_healthy
      wms:
        condition: service_healthy
      wfs:
        condition: service_healthy
      gwc:
        condition: service_healthy
      rest:
        condition: service_healthy
      #webui:
      #  condition: service_started
      #wps:
      #  condition: service_started
      #wcs:
      #  condition: service_healthy
    deploy:
      mode: replicated
      replicas: 0
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  # For github CI
  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  postgis:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
  acl:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  gateway:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  discovery:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
  config:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
  wms:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    healthcheck:
      retries: 20
  wfs:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    healthcheck:
      retries: 20
  rest:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    healthcheck:
      retries: 20
  gwc:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    healthcheck:
      retries: 20
  webui:
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  wps:
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  wcs:
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  acldb:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
