#
# Configures all geoserver services to use a shared data directory as catalog backend.
# Run with `docker compose -f compose.yml -f catalog-datadir.yml up -d`
# Note the default data directory location is /opt/app/data_directory
# To set it to a different path, change the mount point and add the following env variable: GEOSERVER_DATA_DIR: </path/to/data_directory>

name: gscloud_dev_datadir

volumes:
  data_directory:
#    driver_opts:
#      type: none
#      o: bind
#      device: $PWD/catalog-datadir
  
services:
  init-datadir:
    image: alpine:3.18.4
    user: ${GS_USER}
    command: sh -c "cd /opt/app/data_directory; if [ ! -f global.xml ]; then tar xvzf /tmp/datadir.tgz; fi"
    volumes:
      - data_directory:/opt/app/data_directory
      - ./catalog-datadir.tgz:/tmp/datadir.tgz
  wfs:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  wms:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  wcs:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  wps:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  rest:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  webui:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

  gwc:
    environment:
      SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},datadir"
    depends_on:
      init-datadir:
        condition: service_completed_successfully
    volumes:
      - data_directory:/opt/app/data_directory:z

