#!/bin/sh
set -e
# Change to the directory where the script is located
cd "$(dirname "$0")"

mkdir -p catalog-datadir

GSUID=$(id -u)
GSGID=$(id -g)

GS_USER="$GSUID:$GSGID" \
docker compose -f compose.yml -f catalog-datadir.yml "$@"
