volumes:
  #rabbitmq_data: # volume for rabbitmq data, so it doesn't create an anonymous one on each container
  geodatabase_data:

services:
  geodatabase:
    extends:
      file: templates.yml
      service: postgistemplate
    shm_size: 1g
    environment:
      POSTGRES_DB: geoserver
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    volumes:
      - ./pg_entrypoint:/docker-entrypoint-initdb.d:ro
      - geodatabase_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoserver"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 2g

  rabbitmq:
    image: rabbitmq:4-management-alpine
    user: ${GS_USER}
    tmpfs:
      - /var/lib/rabbitmq
    volumes:
      - $PWD/../config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:Z
    #  - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics is_running
      start_period: 10s
      interval: 15s
      timeout: 30s
      retries: 3

  # Sample LDAP server to test LDAP Auth against
  # Go to Authentication -> Authentication Providers -> Add new -> LDAP
  # * Server URL: ldap://ldap:389/dc=georchestra,dc=org
  # * User lookup pattern: uid={0},ou=users
  # * Use LDAP groups for authorization: check
  # * Enable Hierarchical groups search: check
  # * Nested group search filter: member={0}
  # Save
  # Provider Chain -> add the ldap provider to the "Selected" list
  # Save
  # Then login with either testadmin/testadmin or testuser/testuser
  ldap:
    image: georchestra/ldap:latest
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD=secret
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    restart: unless-stopped
    ports:
      - 389:389
    deploy:
      mode: replicated
      replicas: 0
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
