# Standalone mode configuration for GeoServer Cloud
# - Replaces infrastructure services with dummy containers
# - Applies standalone profile to all GeoServer services
# - Works with various catalog backends (datadir, jdbcconfig, pgconfig)

services:
  # Replace infrastructure services with minimal Alpine containers
  discovery:
    image: alpine:latest
    entrypoint: ["sh", "-c", "echo 'Discovery service is disabled in standalone mode' && tail -f /dev/null"]
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  config:
    image: alpine:latest
    entrypoint: ["sh", "-c", "echo 'Config service is disabled in standalone mode' && tail -f /dev/null"]
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  admin:
    image: alpine:latest
    entrypoint: ["sh", "-c", "echo 'Admin service is disabled in standalone mode' && tail -f /dev/null"]
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  # Apply standalone profile to all services
  gateway:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
  
  wfs:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  wms:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  wcs:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  wps:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  rest:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  webui:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
  
  gwc:
    environment:
      SPRING_PROFILES_INCLUDE: "standalone"
    depends_on:
      discovery:
        condition: service_healthy
        required: false
      rabbitmq:
        condition: service_healthy
        required: true
