/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.spring.config.transpiler.generator;

import static org.geoserver.spring.config.transpiler.xml.EnhancedBeanDefinition.sanitizeBeanName;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.MethodSpec.Builder;
import java.beans.BeanInfo;
import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import java.lang.reflect.Constructor;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Stream;
import org.geoserver.spring.config.transpiler.context.BeanGenerationContext;
import org.geoserver.spring.config.transpiler.context.TranspilationContext;
import org.jspecify.annotations.Nullable;
import org.springframework.beans.PropertyValue;
import org.springframework.beans.PropertyValues;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.config.BeanDefinitionHolder;
import org.springframework.beans.factory.config.ConstructorArgumentValues;
import org.springframework.beans.factory.config.RuntimeBeanReference;
import org.springframework.beans.factory.config.TypedStringValue;
import org.springframework.beans.factory.support.ManagedList;
import org.springframework.beans.factory.support.ManagedMap;
import org.springframework.beans.factory.support.ManagedProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.DependsOn;
import org.springframework.util.StringUtils;

/**
 * Abstract base class for bean method generators that provides common functionality.
 *
 * <p>This base class contains shared logic for:
 *
 * <ul>
 *   <li>Creating {@code @Bean} annotations with proper name handling
 *   <li>Common utility methods for bean method generation
 * </ul>
 *
 * @since 3.0.0
 */
@SuppressWarnings("java:S1192")
public abstract class AbstractBeanMethodGenerator implements BeanMethodGenerator {

    /**
     * Create {@code @Bean} annotation with proper name handling for all bean names (original + aliases). This logic
     * handles both single names and multiple names correctly.
     *
     * @param beanContext the bean generation context containing name information
     * @return properly configured {@code @Bean} annotation
     */
    protected AnnotationSpec createBeanAnnotation(BeanGenerationContext beanContext) {
        AnnotationSpec.Builder beanAnnotationBuilder = AnnotationSpec.builder(Bean.class);

        // Get all names using the utility method from BeanGenerationContext
        List<String> allNames = beanContext.getAllNames();

        // Include name parameter based on consolidated EnhancedBeanInfo logic, with
        // special handling for aliases
        boolean shouldIncludeName = beanContext.shouldIncludeInBeanAnnotation();

        // For non-auto-generated names, include name parameter if there are aliases
        // But for auto-generated names (e.g., ClassName#0), respect the original
        // decision
        if (!shouldIncludeName && !beanContext.isAutoGenerated()) {
            // Only override for non-auto-generated names when there are aliases
            shouldIncludeName = !beanContext.getAliases().isEmpty();
        }

        if (shouldIncludeName) {
            if (allNames.size() == 1) {
                // Single name
                beanAnnotationBuilder.addMember("name", "$S", allNames.get(0));
            } else {
                // Multiple names (original + aliases) - create array
                CodeBlock.Builder arrayBuilder = CodeBlock.builder().add("{");
                for (int i = 0; i < allNames.size(); i++) {
                    if (i > 0) {
                        arrayBuilder.add(", ");
                    }
                    arrayBuilder.add("$S", allNames.get(i));
                }
                arrayBuilder.add("}");
                beanAnnotationBuilder.addMember("name", arrayBuilder.build());
            }
        }

        return beanAnnotationBuilder.build();
    }

    /** Add {@code @DependsOn} annotation if bean has depends-on attribute */
    protected void addDependsOnAnnotation(MethodSpec.Builder methodBuilder, @Nullable String[] dependsOn) {
        if (dependsOn != null && dependsOn.length > 0) {
            AnnotationSpec.Builder dependsOnBuilder = AnnotationSpec.builder(DependsOn.class);
            if (dependsOn.length == 1) {
                dependsOnBuilder.addMember("value", "$S", dependsOn[0]);
            } else {
                CodeBlock.Builder arrayBuilder = CodeBlock.builder().add("{");
                for (int i = 0; i < dependsOn.length; i++) {
                    if (i > 0) {
                        arrayBuilder.add(", ");
                    }
                    arrayBuilder.add("$S", dependsOn[i]);
                }
                arrayBuilder.add("}");
                dependsOnBuilder.addMember("value", arrayBuilder.build());
            }
            methodBuilder.addAnnotation(dependsOnBuilder.build());
        }
    }

    /**
     * Add @SuppressWarnings annotation if the bean has property values that require it. This is needed when dealing
     * with ManagedMap or ManagedProperties which use raw types.
     *
     * @param methodBuilder the method builder to add the annotation to
     * @param beanDefinition the bean definition to check for managed collections
     */
    protected void addSuppressWarningsIfNeeded(MethodSpec.Builder methodBuilder, BeanDefinition beanDefinition) {
        boolean hasMapProperties = beanDefinition.getPropertyValues().getPropertyValueList().stream()
                .anyMatch(
                        pv -> pv.getValue() instanceof ManagedMap<?, ?> || pv.getValue() instanceof ManagedProperties);

        if (hasMapProperties) {
            AnnotationSpec suppressWarnings = AnnotationSpec.builder(SuppressWarnings.class)
                    .addMember("value", "{$S, $S}", "unchecked", "rawtypes")
                    .build();
            methodBuilder.addAnnotation(suppressWarnings);
        }
    }

    /**
     * Generate a property setter call with proper type conversion based on the target property type. Uses Spring's
     * BeanWrapper introspection for accurate type resolution.
     *
     * @param methodBuilder the method builder to add statements to
     * @param setterName the setter method name (e.g., "setOrder")
     * @param propertyName the property name (e.g., "order")
     * @param stringValue the string value from XML
     * @param beanClassName the bean class name for type introspection
     */
    protected void generateTypedPropertySetterCall(
            MethodSpec.Builder methodBuilder,
            String setterName,
            String propertyName,
            TypedStringValue stringValue,
            String beanClassName) {
        String rawValue = stringValue.getValue();
        generateTypedPropertySetterCall(methodBuilder, "bean", setterName, propertyName, rawValue, beanClassName);
    }

    /**
     * Generate a property setter call with proper type conversion based on the target property type. Uses Spring's
     * BeanWrapper introspection for accurate type resolution.
     *
     * @param methodBuilder the method builder to add statements to
     * @param targetVar the variable name to call the setter on (e.g., "bean" or a nested bean variable)
     * @param setterName the setter method name (e.g., "setOrder")
     * @param propertyName the property name (e.g., "order")
     * @param rawValue the string value from XML
     * @param beanClassName the bean class name for type introspection
     */
    protected void generateTypedPropertySetterCall(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue,
            String beanClassName) {

        if (!StringUtils.hasLength(rawValue)) {
            methodBuilder.addComment("Property %s has empty value, no setter call generated".formatted(propertyName));
            return;
        }

        // Determine the property type using BeanWrapper introspection (fail fast if not found)
        Class<?> propertyType = getPropertyType(propertyName, beanClassName);

        if (Reflections.isPrimitiveOrBoxedType(propertyType)) {
            generatePrimitiveLiteralSetter(propertyType, methodBuilder, targetVar, setterName, propertyName, rawValue);
        } else if (propertyType == Class.class) {
            // Class properties - optimize to use .class literal when possible
            generateOptimizedClassSetter(methodBuilder, targetVar, setterName, rawValue, beanClassName);
        } else if (propertyType == List.class) {
            // List properties - generate List.of() with proper element conversion
            generateListPropertySetter(methodBuilder, targetVar, setterName, rawValue, beanClassName);
        } else if (propertyType.isEnum()) {
            // Enum properties - use enum constant directly
            methodBuilder.addStatement("$L.$L($T.$L)", targetVar, setterName, propertyType, rawValue);
        } else if (propertyType != String.class && Reflections.hasStringConstructor(propertyType)) {
            // Property expects a non-String type that can be constructed from a string
            methodBuilder.addStatement("$L.$L(new $T($S))", targetVar, setterName, propertyType, rawValue);
        } else {
            // String or other object properties (default case)
            methodBuilder.addStatement("$L.$L($S)", targetVar, setterName, rawValue);
        }
    }

    private void generatePrimitiveLiteralSetter(
            Class<?> propertyType,
            Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue) {
        if (propertyType == int.class || propertyType == Integer.class) {
            generateIntegerLiteralSetter(methodBuilder, targetVar, setterName, propertyName, rawValue);
        } else if (propertyType == long.class || propertyType == Long.class) {
            generateLongLiteralSetter(methodBuilder, targetVar, setterName, propertyName, rawValue);
        } else if (propertyType == double.class || propertyType == Double.class) {
            generateDoubleLiteralSetter(methodBuilder, targetVar, setterName, propertyName, rawValue);
        } else if (propertyType == float.class || propertyType == Float.class) {
            generateFloatLiteralSetter(methodBuilder, targetVar, setterName, propertyName, rawValue);
        } else if (propertyType == boolean.class || propertyType == Boolean.class) {
            generateBooleanLiteralSetter(methodBuilder, targetVar, setterName, rawValue);
        } else {
            throw new UnsupportedOperationException(
                    "Unhandled primitive literal type: " + propertyType.getCanonicalName());
        }
    }

    private void generateFloatLiteralSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue) {
        try {
            Float.parseFloat(rawValue); // Validate it's a valid float
            methodBuilder.addStatement("$L.$L($LF)", targetVar, setterName, rawValue);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "Property '%s' expects a float but got: '%s'".formatted(propertyName, rawValue), e);
        }
    }

    private void generateDoubleLiteralSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue) {
        try {
            Double.parseDouble(rawValue); // Validate it's a valid double
            methodBuilder.addStatement("$L.$L($LD)", targetVar, setterName, rawValue);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "Property '%s' expects a double but got: '%s'".formatted(propertyName, rawValue), e);
        }
    }

    private void generateLongLiteralSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue) {
        try {
            Long.parseLong(rawValue); // Validate it's a valid long
            methodBuilder.addStatement("$L.$L($LL)", targetVar, setterName, rawValue);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "Property '%s' expects a long but got: '%s'".formatted(propertyName, rawValue), e);
        }
    }

    private void generateIntegerLiteralSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String propertyName,
            String rawValue) {
        try {
            Integer.parseInt(rawValue); // Validate it's a valid integer
            methodBuilder.addStatement("$L.$L($L)", targetVar, setterName, rawValue);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "Property '%s' expects an integer but got: '%s'".formatted(propertyName, rawValue), e);
        }
    }

    private void generateBooleanLiteralSetter(
            MethodSpec.Builder methodBuilder, String targetVar, String setterName, String rawValue) {
        boolean boolValue = "true".equalsIgnoreCase(rawValue);
        methodBuilder.addStatement("$L.$L($L)", targetVar, setterName, boolValue);
    }

    /**
     * Get the property type for a given property name using Java Beans introspection. This provides accurate type
     * information for proper code generation without requiring class instantiation.
     *
     * @param propertyName the property name to introspect
     * @param beanClassName the fully qualified bean class name
     * @return the property type class
     * @throws IllegalArgumentException if property is not found
     * @throws RuntimeException if class cannot be loaded or introspected
     */
    protected Class<?> getPropertyType(String propertyName, String beanClassName) {
        if (beanClassName == null) {
            throw new IllegalArgumentException("Bean class name cannot be null for property type resolution");
        }

        Class<?> beanClass = Reflections.convertToRuntimeClass(beanClassName);
        try {
            // Use Java Beans Introspector to analyze properties without instantiation
            BeanInfo beanInfo = Introspector.getBeanInfo(beanClass);
            PropertyDescriptor[] propertyDescriptors = beanInfo.getPropertyDescriptors();

            // Find the property descriptor for the specific property
            for (PropertyDescriptor propertyDescriptor : propertyDescriptors) {
                if (propertyName.equals(propertyDescriptor.getName())) {
                    return propertyDescriptor.getPropertyType();
                }
            }

            throw new IllegalArgumentException(
                    "Property '%s' not found on class %s".formatted(propertyName, beanClassName));

        } catch (Exception e) {
            throw new IllegalStateException(
                    "Failed to introspect property '%s' on class %s".formatted(propertyName, beanClassName), e);
        }
    }

    /**
     * Extract the actual string value from Spring framework objects like TypedStringValue. This handles the common case
     * where XML values are wrapped in Spring's internal objects.
     *
     * @param obj the object to extract value from
     * @return the string value
     */
    protected String extractStringValue(Object obj) {
        return switch (obj) {
            case TypedStringValue value -> value.getValue();
            case String string -> string;
            default -> obj.toString();
        };
    }

    /**
     * Extract simple SpEL bean reference from a string value. Returns the bean name if the value is a simple SpEL
     * expression like #{beanName}, otherwise returns null.
     */
    @SuppressWarnings("java:S125")
    protected String extractSimpleSpelBeanReference(String value) {
        if (value == null || value.trim().isEmpty()) {
            return null;
        }

        String trimmed = value.trim();

        // Check if it's a simple SpEL bean reference: #{beanName}
        if (trimmed.startsWith("#{") && trimmed.endsWith("}")) {
            String spelContent = trimmed.substring(2, trimmed.length() - 1).trim();

            // Simple bean reference: just a valid Java identifier (no operators, spaces, quotes, etc.)
            if (spelContent.matches("^[a-zA-Z_]\\w*$")) {
                return spelContent;
            }
        }

        return null;
    }

    /**
     * Generate a ManagedList constructor call using ArrayList with bean references. Based on the pattern from the old
     * spring-factory-processor ManagedListHelper. This creates a list constructor argument where bean references become
     * method parameters. Uses ArrayList instead of List.of() for Spring runtime compatibility.
     *
     * @param managedList the ManagedList to process
     * @return the generated ArrayList construction call string
     */
    protected String generateManagedListCall(ManagedList<?> managedList) {
        StringBuilder listCall = new StringBuilder("new java.util.ArrayList<>(java.util.List.of(");

        boolean first = true;
        for (Object listItem : managedList) {
            if (!first) {
                listCall.append(", ");
            }
            first = false;

            switch (listItem) {
                case RuntimeBeanReference beanRef -> {
                    // Use sanitized bean name as parameter - this must match the method parameter names
                    String sanitizedBeanName = sanitizeBeanName(beanRef.getBeanName());
                    listCall.append(sanitizedBeanName);
                }
                case org.springframework.beans.factory.config.TypedStringValue stringValue ->
                    // Extract the actual string value from TypedStringValue
                    listCall.append("\"").append(stringValue.getValue()).append("\"");
                default ->
                    // Other types - don't know how to proceed
                    throw new UnsupportedOperationException(
                            "Unsupported ManagedList item to generate a managed list call: %s".formatted(listItem));
            }
        }
        listCall.append("))");
        return listCall.toString();
    }

    /**
     * Collect bean references from a ManagedList. This is used to determine which method parameters need to be added
     * for list constructor arguments.
     *
     * @param managedList the ManagedList to analyze
     * @return list of bean reference names that should become method parameters
     */
    protected List<String> collectBeanReferencesFromManagedList(ManagedList<?> managedList) {
        // Note: getBeanName() returns raw names, callers should sanitize if needed for JavaPoet
        return managedList.stream()
                .filter(RuntimeBeanReference.class::isInstance)
                .map(RuntimeBeanReference.class::cast)
                .map(RuntimeBeanReference::getBeanName)
                .toList();
    }

    /**
     * Collect bean references from property values, including references inside ManagedList and SpEL references inside
     * ManagedProperties. Returns <strong>original (unsanitized)</strong> bean names. Callers that need sanitized names
     * for use as Java identifiers should post-process the result with {@code sanitizeBeanName()}.
     */
    protected List<String> collectPropertyBeanReferences(PropertyValues propertyValues) {
        List<String> beanReferences = new ArrayList<>();
        for (PropertyValue pv : propertyValues.getPropertyValues()) {
            Object value = pv.getValue();
            if (value instanceof RuntimeBeanReference beanRef) {
                beanReferences.add(beanRef.getBeanName());
            } else if (value instanceof ManagedProperties managedProps) {
                collectPropertyBeanReferences(beanReferences, managedProps);
            } else if (value instanceof ManagedList<?> managedList) {
                collectPropertyBeanReferences(beanReferences, managedList);
            }
        }
        return beanReferences;
    }

    /** Collect bean references from a ManagedList into the given list, deduplicating. */
    protected void collectPropertyBeanReferences(List<String> beanReferences, ManagedList<?> managedList) {
        for (String beanRef : collectBeanReferencesFromManagedList(managedList)) {
            if (!beanReferences.contains(beanRef)) {
                beanReferences.add(beanRef);
            }
        }
    }

    /** Collect SpEL bean references from ManagedProperties into the given list, deduplicating. */
    protected void collectPropertyBeanReferences(List<String> beanReferences, ManagedProperties managedProps) {
        for (Object propVal : managedProps.values()) {
            String propValStr = extractStringValue(propVal);
            String simpleBeanRef = extractSimpleSpelBeanReference(propValStr);
            if (simpleBeanRef != null && !beanReferences.contains(simpleBeanRef)) {
                beanReferences.add(simpleBeanRef);
            }
        }
    }

    /**
     * Resolve parameter type for a bean reference using TypeNameResolver. This provides consistent type resolution
     * across all generators.
     *
     * @param beanName the bean name to resolve type for
     * @param transpilationContext the transpilation context containing bean definitions
     * @return the resolved parameter type as ClassName
     */
    protected ClassName resolveParameterType(String beanName, TranspilationContext transpilationContext) {

        Map<String, BeanDefinition> allBeanDefinitions = transpilationContext.getAllBeanDefinitions();
        if (allBeanDefinitions == null || allBeanDefinitions.isEmpty()) {
            return ClassName.get(Object.class);
        }

        TypeNameResolver.TypeResolutionResult result =
                TypeNameResolver.resolveDependencyType(beanName, allBeanDefinitions, transpilationContext);

        if (!result.isResolved()) {
            return ClassName.get(Object.class);
        }

        return typeNameToClassName(result.getResolvedTypeName());
    }

    /**
     * Resolve the return type for a {@code @Bean} method using {@link TypeNameResolver}. Returns {@code Object.class}
     * if the type cannot be resolved. If the resolved class is not public (and thus not accessible from a generated
     * {@code @Bean} method in another package), falls back to its nearest public ancestor.
     */
    protected ClassName resolveReturnType(BeanDefinition beanDefinition, TranspilationContext context) {
        TypeNameResolver.TypeResolutionResult result = TypeNameResolver.resolveBeanReturnType(beanDefinition, context);
        if (!result.isResolved()) {
            return ClassName.get(Object.class);
        }
        return toAccessibleClassName(result.getResolvedTypeName());
    }

    /**
     * Convert a fully qualified type name to a {@link ClassName}, substituting the nearest public ancestor if the class
     * itself is not public. {@code @Bean} method return/parameter types must be accessible from the generated
     * configuration class, which lives in a different package than Spring Security internals such as
     * {@code HttpSecurityConfiguration}.
     */
    protected ClassName toAccessibleClassName(String typeName) {
        try {
            Class<?> clazz = Reflections.convertToRuntimeClass(typeName);
            if (!Reflections.isPublic(clazz)) {
                return ClassName.get(Reflections.findFirstPublicAncestor(clazz));
            }
        } catch (IllegalStateException _) {
            // Reflections.convertToRuntimeClass wraps ClassNotFoundException — the class isn't on the
            // annotation-processor classpath. Fall through to emit the literal name; downstream compile
            // errors will point to the real missing dependency.
        }
        return typeNameToClassName(typeName);
    }

    /** Convert a fully qualified type name string to a JavaPoet ClassName. Falls back to Object on failure. */
    protected ClassName typeNameToClassName(String typeName) {
        try {
            if (typeName.contains(".")) {
                int lastDot = typeName.lastIndexOf('.');
                String packageName = typeName.substring(0, lastDot);
                String simpleName = typeName.substring(lastDot + 1);
                return ClassName.get(packageName, simpleName);
            } else {
                return ClassName.get("java.lang", typeName);
            }
        } catch (Exception _) {
            return ClassName.get(Object.class);
        }
    }

    /**
     * Resolve parameter type for bean references with enhanced type inference. This method tries multiple strategies to
     * find the most appropriate parameter type:
     *
     * <ul>
     *   <li>1. Constructor parameter type (if paramIndex provided and beanClassName available)
     *   <li>2. Property setter parameter type (if propertyName provided and beanClassName available)
     *   <li>3. Fallback to referenced bean's type
     * </ul>
     *
     * @param beanName the name of the referenced bean
     * @param beanClassName the class name of the bean being created (for reflection)
     * @param paramIndex optional constructor parameter index (for constructor injection)
     * @param propertyName optional property name (for setter injection)
     * @param constructorArgs optional constructor arguments (for parameter count validation)
     * @param transpilationContext the transpilation context
     * @return the resolved parameter type
     */
    protected ClassName resolveParameterTypeWithInference(
            String beanName,
            String beanClassName,
            Integer paramIndex,
            String propertyName,
            ConstructorArgumentValues constructorArgs,
            TranspilationContext transpilationContext) {

        // Strategy 1: Constructor parameter type inference
        if (paramIndex != null && beanClassName != null) {
            Class<?> expectedType = getConstructorParameterType(paramIndex, beanClassName, constructorArgs);
            return ClassName.get(expectedType);
        }

        // Strategy 2: Property setter parameter type inference
        if (propertyName != null && beanClassName != null) {
            Class<?> setterParamType = getPropertyType(propertyName, beanClassName);
            if (setterParamType != null) {
                return ClassName.get(setterParamType);
            }
        }

        // Strategy 3: Fallback to referenced bean type
        return resolveParameterType(beanName, transpilationContext);
    }

    /** Get constructor parameter type using reflection. */
    protected Class<?> getConstructorParameterType(
            int paramIndex, String beanClassName, ConstructorArgumentValues constructorArgs) {

        Class<?> beanClass = Reflections.convertToRuntimeClass(beanClassName);
        Constructor<?> constructor = Reflections.resolveTargetConstructor(beanClass, constructorArgs);
        if (constructor != null && paramIndex < constructor.getParameterCount()) {
            return constructor.getParameterTypes()[paramIndex];
        }
        throw new IllegalStateException("Unable to resolve constructor parameter type for index " + paramIndex);
    }
    /**
     * Generate reflection-based constructor instantiation for no-argument constructors. This handles protected/private
     * constructors that can't be called directly.
     *
     * @param methodBuilder the method builder to add statements to
     * @param beanClassName the fully qualified class name
     * @param returnType the return type for casting
     * @param variableName the variable name to create ("bean" for properties, null for direct return)
     */
    protected void generateReflectionConstructorCall(
            MethodSpec.Builder methodBuilder, String beanClassName, ClassName returnType, String variableName) {

        methodBuilder.addStatement(
                "java.lang.reflect.Constructor constructor = java.lang.Class.forName($S).getDeclaredConstructor()",
                beanClassName);
        methodBuilder.addStatement("constructor.setAccessible(true)");

        if (variableName != null) {
            // Create variable for property setting
            methodBuilder.addStatement("$T $L = ($T) constructor.newInstance()", returnType, variableName, returnType);
        } else {
            // Direct return
            methodBuilder.addStatement("return ($T) constructor.newInstance()", returnType);
        }

        // Add exception to method signature for reflection
        methodBuilder.addException(ClassName.get(Exception.class));
    }

    /**
     * Generate a property setter call for nested bean definitions. This handles two patterns: 1.
     * FieldRetrievingFactoryBean pattern: generates static field references 2. Simple object constructor pattern:
     * generates direct instantiation
     */
    protected void generateNestedBeanPropertySetter(
            MethodSpec.Builder methodBuilder, String setterName, BeanDefinitionHolder nestedBeanHolder) {

        BeanDefinition nestedBeanDefinition = nestedBeanHolder.getBeanDefinition();
        String nestedBeanClassName = nestedBeanDefinition.getBeanClassName();

        if (nestedBeanClassName == null) {
            throw new IllegalStateException("Nested bean has no class name - cannot instantiate");
        }

        // Check if this is a FieldRetrievingFactoryBean
        if ("org.springframework.beans.factory.config.FieldRetrievingFactoryBean".equals(nestedBeanClassName)) {
            generateFieldRetrievingFactoryBeanSetter(methodBuilder, setterName, nestedBeanHolder);
            return;
        }

        PropertyValues nestedProps = nestedBeanDefinition.getPropertyValues();
        if (nestedProps.getPropertyValues().length == 0) {
            // No properties on the nested bean: generate direct instantiation
            methodBuilder.addStatement("bean.$L(new $L())", setterName, nestedBeanClassName);
            return;
        }

        // Nested bean has properties: create a local variable, set properties, then assign
        // Derive variable name from the setter: setAuthorizer -> authorizer
        String varName = Character.toLowerCase(setterName.charAt(3)) + setterName.substring(4);
        methodBuilder.addStatement("$L $L = new $L()", nestedBeanClassName, varName, nestedBeanClassName);

        for (org.springframework.beans.PropertyValue pv : nestedProps.getPropertyValues()) {
            final String propertyName = pv.getName();
            final Object value = Objects.requireNonNull(pv.getValue(), "Unsupported null values here");
            final String nestedSetterName = Reflections.buildSetterName(propertyName);

            switch (value) {
                case TypedStringValue stringValue ->
                    generateTypedPropertySetterCall(
                            methodBuilder,
                            varName,
                            nestedSetterName,
                            propertyName,
                            stringValue.getValue(),
                            nestedBeanClassName);
                case ManagedList<?> managedList ->
                    generateNestedBeanManagedListSetter(
                            methodBuilder, varName, nestedSetterName, managedList, nestedBeanClassName);
                default ->
                    // Other types - don't know how to proceed
                    throw new UnsupportedOperationException("Unsupported value for nested setter: " + value);
            }
        }

        methodBuilder.addStatement("bean.$L($L)", setterName, varName);
    }

    private void generateFieldRetrievingFactoryBeanSetter(
            MethodSpec.Builder methodBuilder, String setterName, BeanDefinitionHolder nestedBeanHolder) {
        String beanId = Objects.requireNonNull(nestedBeanHolder.getBeanName());
        if (beanId.contains(".") && Character.isUpperCase(beanId.charAt(beanId.lastIndexOf('.') + 1))) {
            // Bean ID looks like: org.geoserver.catalog.LayerGroupVisibilityPolicy.HIDE_NEVER
            // Generate: bean.setProperty(org.geoserver.catalog.LayerGroupVisibilityPolicy.HIDE_NEVER)
            methodBuilder.addStatement("bean.$L($L)", setterName, beanId);
        } else {
            throw new IllegalStateException("FieldRetrievingFactoryBean with invalid field reference: " + beanId);
        }
    }

    /**
     * Generate a ManagedList setter call on a nested bean variable. Inspects the setter's generic type to convert list
     * elements appropriately (e.g., {@code List<Class<?>>} generates class literals).
     */
    private void generateNestedBeanManagedListSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            ManagedList<?> managedList,
            String beanClassName) {

        // Check if the setter expects List<Class<?>> by inspecting generic type
        SetterTypeInfo typeInfo = getSetterTypeInfo(setterName, beanClassName);
        boolean isClassList =
                typeInfo.genericParameterType instanceof ParameterizedType paramType && isClassList(paramType);

        String parameterArguments = buldListItemsArguments(managedList, isClassList);
        methodBuilder.addStatement("$L.$L(java.util.List.of($L))", targetVar, setterName, parameterArguments);
    }

    private boolean isClassList(ParameterizedType paramType) {
        Type[] typeArgs = paramType.getActualTypeArguments();
        if (typeArgs.length == 1) {
            Type elementType = typeArgs[0];
            if (elementType instanceof ParameterizedType elementParamType
                    && elementParamType.getRawType() == Class.class) {
                return true;
            }
        }
        return false;
    }

    private String buldListItemsArguments(ManagedList<?> managedList, boolean isClassList) {
        StringBuilder listItems = new StringBuilder();
        boolean first = true;
        for (Object listItem : managedList) {
            if (!first) {
                listItems.append(", ");
            }
            first = false;

            String itemValue;
            if (listItem instanceof org.springframework.beans.factory.config.TypedStringValue tsv) {
                itemValue = tsv.getValue();
            } else {
                itemValue = listItem.toString();
            }

            if (isClassList) {
                listItems.append(itemValue).append(".class");
            } else {
                listItems.append("\"").append(itemValue).append("\"");
            }
        }

        return listItems.toString();
    }

    /**
     * Generate property setter method calls with proper type conversion. This unified method handles all property value
     * types and can be used by both SimpleBeanMethodGenerator and ConstructorBasedBeanMethodGenerator.
     *
     * @param methodBuilder the method builder to add statements to
     * @param propertyValues the Spring PropertyValues to process
     * @param beanReferences optional list of bean reference parameter names (for SimpleBeanMethodGenerator)
     * @param beanClassName the bean class name for type introspection
     * @param beanName the bean name for error messages
     */
    protected void generatePropertySetters(
            MethodSpec.Builder methodBuilder,
            PropertyValues propertyValues,
            @Nullable List<String> beanReferences,
            String beanClassName,
            String beanName) {

        if (propertyValues == null || propertyValues.getPropertyValues().length == 0) {
            return;
        }

        int beanRefIndex = 0;

        for (PropertyValue pv : propertyValues.getPropertyValues()) {
            String propertyName = pv.getName();
            Object value = Objects.requireNonNull(pv.getValue(), "null values is not supported here");

            // Generate setter method name
            String setterName = Reflections.buildSetterName(propertyName);

            switch (value) {
                case RuntimeBeanReference beanRef -> {
                    String referencedBeanName = beanRef.getBeanName();

                    if (beanReferences != null && beanRefIndex < beanReferences.size()) {
                        // SimpleBeanMethodGenerator approach: use pre-collected bean reference parameters by index
                        methodBuilder.addStatement("bean.$L($N)", setterName, beanReferences.get(beanRefIndex++));
                    } else {
                        // ConstructorBasedBeanMethodGenerator approach: use sanitized bean name directly
                        methodBuilder.addStatement("bean.$L($N)", setterName, sanitizeBeanName(referencedBeanName));
                    }
                }
                case TypedStringValue stringValue ->
                    generateTypedPropertySetterCall(
                            methodBuilder, setterName, propertyName, stringValue, beanClassName);
                case ManagedProperties managedProps ->
                    generageManagedPropertiesPropertySetter(methodBuilder, propertyName, setterName, managedProps);
                case ManagedMap<?, ?> managedMap ->
                    generageManagedMapPropertySetter(
                            methodBuilder, beanClassName, propertyName, setterName, managedMap);
                case ManagedList<?> managedList ->
                    generageManagedListPropertySetter(methodBuilder, beanClassName, setterName, managedList);
                case BeanDefinitionHolder nestedBeanHolder ->
                    // Handle nested bean definitions
                    generateNestedBeanPropertySetter(methodBuilder, setterName, nestedBeanHolder);
                default -> {
                    String valueType = value.getClass().getSimpleName();
                    throw new UnsupportedOperationException("Unable to generate property setter for property "
                            + propertyName + " of type " + valueType);
                }
            }
        }
    }

    private void generageManagedListPropertySetter(
            MethodSpec.Builder methodBuilder, String beanClassName, String setterName, ManagedList<?> managedList) {
        // Handle ManagedList (like <list> with bean references for method arguments)
        // Check if the setter method expects varargs
        if (isVarargsSetterMethod(setterName, beanClassName)) {
            // Generate varargs call: bean.setInterceptors(item1, item2, ...)
            generateVarargsSetterCall(methodBuilder, setterName, managedList);
        } else {
            // Generate list call: bean.setProperty(new ArrayList<>(...))
            String listCall = generateManagedListCall(managedList);
            methodBuilder.addStatement("bean.$L($L)", setterName, listCall);
        }
    }

    private void generageManagedMapPropertySetter(
            MethodSpec.Builder methodBuilder,
            String beanClassName,
            String propertyName,
            String setterName,
            ManagedMap<?, ?> managedMap) {
        // Handle ManagedMap (like <map>)
        methodBuilder.addComment("// Property '" + propertyName + "' uses ManagedMap");

        // Check if this is a Map<Class<?>, Class<?>> based on property type analysis
        boolean isClassMap = isClassToClassMap(propertyName, beanClassName);

        if (isClassMap) {
            // Use raw Map to avoid complex generic issues - the @SuppressWarnings annotation handles this
            methodBuilder.addStatement("java.util.Map $L = new java.util.HashMap()", propertyName + "Map");
        } else {
            methodBuilder.addStatement(
                    "java.util.Map<String, Object> $L = new java.util.HashMap<>()", propertyName + "Map");
        }

        for (Map.Entry<?, ?> entry : managedMap.entrySet()) {
            String keyStr = extractStringValue(entry.getKey());
            String valStr = extractStringValue(entry.getValue());

            if (isClassMap) {
                // Convert strings to Class literals
                methodBuilder.addStatement("$L.put($L.class, $L.class)", propertyName + "Map", keyStr, valStr);
            } else {
                methodBuilder.addStatement("$L.put($S, $S)", propertyName + "Map", keyStr, valStr);
            }
        }

        methodBuilder.addStatement("bean.$L($L)", setterName, propertyName + "Map");
    }

    private void generageManagedPropertiesPropertySetter(
            MethodSpec.Builder methodBuilder, String propertyName, String setterName, ManagedProperties managedProps) {
        // Handle ManagedProperties (like <props>)
        methodBuilder.addComment("// Property '" + propertyName + "' uses ManagedProperties");
        methodBuilder.addStatement("java.util.Properties $L = new java.util.Properties()", propertyName + "Props");

        // Sort keys for deterministic code generation
        managedProps.keySet().stream()
                .sorted((a, b) -> extractStringValue(a).compareTo(extractStringValue(b)))
                .forEach(key -> {
                    Object val = managedProps.get(key);

                    String keyStr = extractStringValue(key);
                    String valStr = extractStringValue(val);

                    // Check if the value is a simple SpEL bean reference
                    String simpleBeanRef = extractSimpleSpelBeanReference(valStr);
                    if (simpleBeanRef != null) {
                        // Use bean reference parameter variable instead of literal SpEL
                        methodBuilder.addStatement(
                                "$L.setProperty($S, $N)", propertyName + "Props", keyStr, simpleBeanRef);
                    } else {
                        // Use literal string value
                        methodBuilder.addStatement("$L.setProperty($S, $S)", propertyName + "Props", keyStr, valStr);
                    }
                });

        methodBuilder.addStatement("bean.$L($L)", setterName, propertyName + "Props");
    }

    /**
     * Check if a property expects a {@code Map<Class<?>, Class<?>>} by analyzing the property type. This is needed for
     * properties like CustomEditorConfigurer.customEditors.
     */
    protected boolean isClassToClassMap(String propertyName, String beanClassName) {
        try {
            Class<?> propertyType = getPropertyType(propertyName, beanClassName);

            // Check if it's a Map type
            // For now, use a simple heuristic: if the property name contains "editor"
            // and the bean is CustomEditorConfigurer, assume it's a Class->Class map
            boolean isMap = Map.class.isAssignableFrom(propertyType);
            return (isMap
                    && propertyName.toLowerCase().contains("editor")
                    && beanClassName.contains("CustomEditorConfigurer"));
        } catch (Exception _) {
            // If we can't determine the type, assume it's not a class map
            return false;
        }
    }

    /**
     * Check if a setter method expects varargs instead of a List parameter. Uses reflection to examine the method
     * signature.
     */
    protected boolean isVarargsSetterMethod(String setterName, String beanClassName) {
        Class<?> beanClass = Reflections.convertToRuntimeClass(beanClassName);
        java.lang.reflect.Method[] methods = beanClass.getMethods();

        for (java.lang.reflect.Method method : methods) {
            if (method.getName().equals(setterName)) {
                return method.isVarArgs();
            }
        }
        throw new IllegalStateException("setter not found %s.%s".formatted(beanClassName, setterName));
    }

    /** Generate a varargs setter call for ManagedList properties. Generates: bean.setInterceptors(item1, item2, ...) */
    protected void generateVarargsSetterCall(
            MethodSpec.Builder methodBuilder, String setterName, ManagedList<?> managedList) {

        StringBuilder argsBuilder = new StringBuilder();
        boolean first = true;

        for (Object listItem : managedList) {
            if (!first) {
                argsBuilder.append(", ");
            }
            first = false;

            switch (listItem) {
                case RuntimeBeanReference beanRef -> {
                    // Use sanitized bean name as parameter - this must match the method parameter names
                    String sanitizedBeanName = sanitizeBeanName(beanRef.getBeanName());
                    argsBuilder.append(sanitizedBeanName);
                }
                case org.springframework.beans.factory.config.TypedStringValue stringValue ->
                    // Extract the actual string value from TypedStringValue
                    argsBuilder.append("\"").append(stringValue.getValue()).append("\"");
                default ->
                    // Other types - don't know how to proceed
                    throw new UnsupportedOperationException(
                            "Unsupported ManagedList item to generate a varargs setter call: %s".formatted(listItem));
            }
        }

        methodBuilder.addStatement("bean.$L($L)", setterName, argsBuilder.toString());
    }

    /**
     * Generate an array initialization call for ManagedList constructor arguments. This creates array syntax like: new
     * String[]{"value1", "value2"}
     *
     * @param managedList the ManagedList to process
     * @param componentType the array component type
     * @return the generated array initialization string
     */
    protected String generateManagedListAsArray(ManagedList<?> managedList, Class<?> componentType) {

        String componentTypeName = componentType.getSimpleName();
        StringBuilder arrayCall =
                new StringBuilder("new ").append(componentTypeName).append("[]{");

        boolean first = true;
        for (Object listItem : managedList) {
            if (!first) {
                arrayCall.append(", ");
            }
            first = false;

            switch (listItem) {
                case RuntimeBeanReference beanRef -> {
                    // Use sanitized bean name as parameter - this must match the method parameter names
                    String sanitizedBeanName = sanitizeBeanName(beanRef.getBeanName());
                    arrayCall.append(sanitizedBeanName);
                }
                case org.springframework.beans.factory.config.TypedStringValue stringValue ->
                    // Extract the actual string value from TypedStringValue
                    arrayCall.append("\"").append(stringValue.getValue()).append("\"");
                default ->
                    // Other types - don't know how to proceed
                    throw new UnsupportedOperationException(
                            "Unsupported ManagedList item to generate a managed list array: %s".formatted(listItem));
            }
        }
        arrayCall.append("}");
        return arrayCall.toString();
    }

    /**
     * Generate an optimized Class property setter call. Uses .class literal when the class is assignable to the
     * expected type, otherwise uses Class.forName() with cast to handle type incompatibilities.
     *
     * @param methodBuilder the method builder to add statements to
     * @param setterName the setter method name
     * @param className the fully qualified class name from XML
     * @param beanClassName the bean class name for reflection
     */
    protected void generateOptimizedClassSetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String className,
            String beanClassName) {

        try {
            Class<?> beanClass = Reflections.convertToRuntimeClass(beanClassName);
            SetterTypeInfo typeInfo = getSetterTypeInfo(setterName, beanClassName);
            // If the bean class is itself generic, the generated code uses the raw type,
            // which erases all type parameters — any .class literal is accepted by the compiler
            boolean beanClassIsGeneric = beanClass.getTypeParameters().length > 0;
            if (typeInfo.canAcceptClassLiteral(className, beanClassIsGeneric)) {
                methodBuilder.addStatement("$L.$L($L.class)", targetVar, setterName, className);
            } else {
                // Invariant generic type — use raw cast of .class literal to bypass generics invariance
                methodBuilder.addStatement("$L.$L((Class) $L.class)", targetVar, setterName, className);
            }
        } catch (Exception e) {
            throw new IllegalStateException("Error generating class setter", e);
        }
    }

    /**
     * Generate a setter call for List-typed properties from a comma-separated string value. Inspects the generic type
     * parameter to generate proper element conversion (e.g., List.of(Foo.class) for List&lt;Class&lt;?&gt;&gt;).
     */
    @SuppressWarnings("java:S3776")
    private void generateListPropertySetter(
            MethodSpec.Builder methodBuilder,
            String targetVar,
            String setterName,
            String rawValue,
            String beanClassName) {

        // Try to determine the generic element type of the List
        SetterTypeInfo typeInfo = getSetterTypeInfo(setterName, beanClassName);
        if (typeInfo.genericParameterType instanceof ParameterizedType paramType) {
            Type[] typeArgs = paramType.getActualTypeArguments();
            if (typeArgs.length == 1) {
                Type elementType = typeArgs[0];
                // Check if it's List<Class<?>> or List<Class<SomeType>>
                if (elementType instanceof ParameterizedType elementParamType
                        && elementParamType.getRawType() == Class.class) {
                    // Split comma-separated class names and generate List.of(Foo.class, Bar.class)
                    String[] classNames = rawValue.split(",");
                    StringBuilder listItems = new StringBuilder();
                    for (int i = 0; i < classNames.length; i++) {
                        if (i > 0) {
                            listItems.append(", ");
                        }
                        listItems.append(classNames[i].trim()).append(".class");
                    }
                    methodBuilder.addStatement(
                            "$L.$L(java.util.List.of($L))", targetVar, setterName, listItems.toString());
                    return;
                }
            }
        }
        // Fallback: treat as List of strings
        String[] items = rawValue.split(",");
        StringBuilder listItems = new StringBuilder();
        for (int i = 0; i < items.length; i++) {
            if (i > 0) {
                listItems.append(", ");
            }
            listItems.append("\"").append(items[i].trim()).append("\"");
        }
        methodBuilder.addStatement("$L.$L(java.util.List.of($L))", targetVar, setterName, listItems.toString());
    }

    /**
     * Get detailed type information for a setter method including generic types.
     *
     * @param setterName the setter method name
     * @param beanClassName the bean class name
     * @return detailed type information
     */
    private SetterTypeInfo getSetterTypeInfo(String setterName, String beanClassName) {

        Class<?> beanClass = Reflections.convertToRuntimeClass(beanClassName);

        for (java.lang.reflect.Method method : beanClass.getMethods()) {
            if (method.getName().equals(setterName) && method.getParameterCount() == 1) {
                Class<?> parameterType = method.getParameterTypes()[0];
                // Use ResolvableType to resolve type variables against the concrete class
                Type genericParameterType = org.springframework.core.ResolvableType.forMethodParameter(
                                method, 0, beanClass)
                        .getType();
                return new SetterTypeInfo(parameterType, genericParameterType);
            }
        }

        throw new IllegalStateException(
                "unable to generate setter type info for %s.%s".formatted(beanClassName, setterName));
    }

    /** Container for setter method type information including generic types. */
    private static class SetterTypeInfo {
        final Class<?> parameterType;
        final Type genericParameterType;

        SetterTypeInfo(Class<?> parameterType, Type genericParameterType) {
            this.parameterType = parameterType;
            this.genericParameterType = genericParameterType;
        }

        /**
         * Check if a {@code .class} literal for the given class name can be passed to this setter without a compiler
         * error. Handles Java generics invariance rules:
         *
         * <ul>
         *   <li>Raw {@code Class} or {@code Class<?>}: any {@code .class} literal works
         *   <li>{@code Class<? extends T>} (wildcard): works if the class extends T
         *   <li>{@code Class<T>} (invariant): works only if the class IS exactly T
         * </ul>
         */
        /**
         * Check if a {@code .class} literal can be used for this setter parameter.
         *
         * @param beanClassIsGeneric whether the bean class itself declares type parameters — if so, the generated code
         *     uses the raw type which erases all generics, making any .class literal acceptable
         */
        boolean canAcceptClassLiteral(String className, boolean beanClassIsGeneric) {
            if (parameterType != Class.class) {
                return false;
            }
            if (!(genericParameterType instanceof ParameterizedType paramType)) {
                return true; // Raw Class — any .class works
            }
            Type[] typeArgs = paramType.getActualTypeArguments();
            if (typeArgs.length != 1) {
                return true;
            }
            try {
                return canAcceptClassLiteral(typeArgs[0], className, beanClassIsGeneric);
            } catch (TypeNotPresentException _) {
                return false; // Bound type not on classpath
            }
        }

        private boolean canAcceptClassLiteral(Type typeArg, String className, boolean beanClassIsGeneric) {
            return switch (typeArg) {
                case java.lang.reflect.WildcardType wildcard -> {
                    // Class<? extends T> — .class works if the class is assignable to the upper bound
                    Type[] upperBounds = wildcard.getUpperBounds();
                    if (upperBounds.length == 1 && upperBounds[0] instanceof Class<?> bound) {
                        yield isClassAssignableToGenericBound(className, bound);
                    }
                    yield true; // Class<?> or unbounded wildcard
                }
                case Class<?> exactType ->
                    // Class<T> (invariant, fully resolved) — .class works only if the class IS exactly T
                    isExactClass(className, exactType);
                case java.lang.reflect.TypeVariable<?> _ ->
                    // Unresolved type variable (e.g., MenuPageInfo<T>.setComponentClass(Class<T>)).
                    // Only safe when the bean class is generic — the generated code uses the raw type,
                    // so the compiler erases T and accepts any .class literal
                    beanClassIsGeneric;
                default -> false;
            };
        }

        /**
         * Check if a class is assignable to a generic bound type.
         *
         * @param className the fully qualified class name to check
         * @param boundClass the generic bound class
         * @return true if the class is assignable to the bound
         */
        private static boolean isClassAssignableToGenericBound(String className, Class<?> boundClass) {
            try {
                Class<?> providedClass = Class.forName(className);
                return boundClass.isAssignableFrom(providedClass);
            } catch (ClassNotFoundException _) {
                return false;
            }
        }

        private boolean isExactClass(String className, Class<?> expected) {
            try {
                return Class.forName(className) == expected;
            } catch (ClassNotFoundException _) {
                return false;
            }
        }
    }

    /**
     * Add checked exceptions from a pre-resolved constructor to the method signature. If the constructor is non-public
     * and {@code reflectionBased} is true, adds a generic {@code throws Exception} instead.
     */
    protected void addExceptionsFromConstructor(
            MethodSpec.Builder methodBuilder, @Nullable Constructor<?> constructor, boolean reflectionBased) {
        if (constructor == null) {
            return;
        }
        Stream<Class<?>> exceptionTypes;
        if (reflectionBased && !Reflections.isPublic(constructor)) {
            exceptionTypes = Stream.of(Exception.class);
        } else {
            exceptionTypes = Stream.of(constructor.getExceptionTypes());
        }
        exceptionTypes
                .filter(e -> Exception.class.isAssignableFrom(e) && !RuntimeException.class.isAssignableFrom(e))
                .map(ClassName::get)
                .forEach(methodBuilder::addException);
    }
}
