/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.spring.config.transpiler.generator;

import static javax.tools.Diagnostic.Kind.NOTE;
import static javax.tools.Diagnostic.Kind.WARNING;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.beans.Introspector;
import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.geoserver.spring.config.transpiler.context.ComponentScanInfo;
import org.geoserver.spring.config.transpiler.context.TranspilationContext;
import org.jspecify.annotations.Nullable;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * Generates {@code @Bean} methods for component-scanned classes discovered at build time.
 *
 * <p>This generator performs classpath scanning using Spring's {@link ClassPathScanningCandidateComponentProvider}
 * during the annotation processing phase, discovering {@code @Component}-annotated classes and generating equivalent
 * {@code @Bean} methods. The generated methods are placed in a static inner {@code @Configuration} class.
 *
 * @since 3.0.0
 */
public class ComponentScanBeanGenerator {

    /**
     * Generate an inner {@code @Configuration} class containing {@code @Bean} methods for all component-scanned beans.
     *
     * @param componentScans the component scan configurations from XML
     * @param context the transpilation context
     * @return the inner class TypeSpec, or {@code null} if no beans were discovered
     */
    public @Nullable TypeSpec generateComponentScannedBeans(
            List<ComponentScanInfo> componentScans, TranspilationContext context) {

        List<MethodSpec> beanMethods = new ArrayList<>();

        // Track discovered FQCNs to avoid duplicates across multiple component-scan elements
        Set<String> discoveredClasses = new LinkedHashSet<>();

        // Track scanned packages and skipped classes for javadoc
        List<String> scannedPackages = new ArrayList<>();
        // bean name -> FQCN for included beans
        Map<String, String> includedBeans = new LinkedHashMap<>();
        // bean name -> FQCN + reason for skipped beans
        Map<String, String> skippedBeans = new LinkedHashMap<>();

        for (ComponentScanInfo scanInfo : componentScans) {
            scanPackages(
                    scanInfo, context, discoveredClasses, beanMethods, scannedPackages, includedBeans, skippedBeans);
        }

        if (beanMethods.isEmpty()) {
            return null;
        }

        // Build inner @Configuration class
        AnnotationSpec configAnnotation = AnnotationSpec.builder(Configuration.class)
                .addMember("proxyBeanMethods", "false")
                .build();

        TypeSpec.Builder innerClassBuilder = TypeSpec.classBuilder("ComponentScannedBeans")
                .addModifiers(javax.lang.model.element.Modifier.STATIC)
                .addAnnotation(configAnnotation);

        addInnerClassJavadoc(innerClassBuilder, scannedPackages, includedBeans, skippedBeans);

        for (MethodSpec method : beanMethods) {
            innerClassBuilder.addMethod(method);
        }

        return innerClassBuilder.build();
    }

    private void addInnerClassJavadoc(
            TypeSpec.Builder classBuilder,
            List<String> scannedPackages,
            Map<String, String> includedBeans,
            Map<String, String> skippedBeans) {

        classBuilder.addJavadoc(
                "Bean definitions generated by build-time component scanning (replaces runtime {@code @ComponentScan}).\n");
        classBuilder.addJavadoc("\n");

        classBuilder.addJavadoc("<p>Scanned packages:\n<ul>\n");
        for (String pkg : scannedPackages) {
            classBuilder.addJavadoc(" <li>{@code $L}</li>\n", pkg);
        }
        classBuilder.addJavadoc("</ul>\n");

        classBuilder.addJavadoc("\n<p>Discovered components:\n<ul>\n");
        for (Map.Entry<String, String> entry : includedBeans.entrySet()) {
            classBuilder.addJavadoc(" <li>{@code $L} &mdash; {@code $L}</li>\n", entry.getKey(), entry.getValue());
        }
        classBuilder.addJavadoc("</ul>\n");

        if (!skippedBeans.isEmpty()) {
            classBuilder.addJavadoc("\n<p>Skipped:\n<ul>\n");
            for (Map.Entry<String, String> entry : skippedBeans.entrySet()) {
                classBuilder.addJavadoc(" <li>{@code $L} &mdash; $L</li>\n", entry.getKey(), entry.getValue());
            }
            classBuilder.addJavadoc("</ul>\n");
        }
    }

    private void scanPackages(
            ComponentScanInfo scanInfo,
            TranspilationContext context,
            Set<String> discoveredClasses,
            List<MethodSpec> beanMethods,
            List<String> scannedPackages,
            Map<String, String> includedBeans,
            Map<String, String> skippedBeans) {

        ClassPathScanningCandidateComponentProvider scanner =
                new ClassPathScanningCandidateComponentProvider(scanInfo.isUseDefaultFilters());
        scanner.setResourceLoader(
                new PathMatchingResourcePatternResolver(getClass().getClassLoader()));

        String resourcePattern = scanInfo.getResourcePattern();
        if (resourcePattern != null && !resourcePattern.trim().isEmpty()) {
            scanner.setResourcePattern(resourcePattern);
        }

        for (String basePackage : scanInfo.getBasePackages()) {
            String pkg = basePackage.trim();
            if (pkg.isEmpty()) continue;

            scannedPackages.add(pkg);
            context.printMessage(NOTE, "Component scanning package: " + pkg);

            Set<BeanDefinition> candidates = scanner.findCandidateComponents(pkg);
            context.printMessage(NOTE, "Found %d candidate components in %s".formatted(candidates.size(), pkg));

            for (BeanDefinition candidate : candidates) {
                String fqcn = candidate.getBeanClassName();
                if (fqcn == null || !discoveredClasses.add(fqcn)) {
                    continue; // skip nulls and duplicates
                }

                MethodSpec method = generateBeanMethodForComponent(fqcn, pkg, context, skippedBeans);
                if (method != null) {
                    beanMethods.add(method);
                    includedBeans.put(method.name(), fqcn);
                }
            }
        }
    }

    private @Nullable MethodSpec generateBeanMethodForComponent(
            String fqcn, String basePackage, TranspilationContext context, Map<String, String> skippedBeans) {
        // Compute default bean name (Spring convention: Introspector.decapitalize)
        String simpleName = fqcn.substring(fqcn.lastIndexOf('.') + 1);
        String beanName = Introspector.decapitalize(simpleName);

        // Check include/exclude patterns
        if (!context.shouldIncludeComponentScannedBean(fqcn, beanName)) {
            context.printMessage(NOTE, "Excluding component-scanned bean: %s (%s)".formatted(beanName, fqcn));
            skippedBeans.put(fqcn, "excluded by pattern");
            return null;
        }

        // Load the class via reflection
        Class<?> beanClass;
        try {
            beanClass = Class.forName(fqcn, false, getClass().getClassLoader());
        } catch (ClassNotFoundException e) {
            context.printMessage(WARNING, "Cannot load component class %s: %s".formatted(fqcn, e.getMessage()));
            skippedBeans.put(fqcn, "class not found: " + e.getMessage());
            return null;
        }

        // Skip abstract classes and interfaces
        if (java.lang.reflect.Modifier.isAbstract(beanClass.getModifiers()) || beanClass.isInterface()) {
            context.printMessage(NOTE, "Skipping abstract/interface component: " + fqcn);
            skippedBeans.put(fqcn, beanClass.isInterface() ? "interface" : "abstract class");
            return null;
        }

        // Skip member classes (inner/nested) — Spring auto-discovers them when the enclosing class is registered
        if (beanClass.getEnclosingClass() != null) {
            context.printMessage(NOTE, "Skipping member class component: " + fqcn);
            skippedBeans.put(
                    fqcn, "member class of " + beanClass.getEnclosingClass().getName());
            return null;
        }

        // Resolve constructor
        Constructor<?> constructor = resolveConstructor(beanClass);
        boolean needsReflection = constructor != null && !Reflections.isPublic(constructor);

        ClassName returnType = ClassName.get(beanClass);

        MethodSpec.Builder methodBuilder =
                MethodSpec.methodBuilder(beanName).addAnnotation(Bean.class).returns(returnType);

        // Add javadoc documenting origin
        String xmlSources = String.join(", ", context.getXmlLocations());
        methodBuilder.addJavadoc(
                "{@code $L} discovered through\n{@code <context:component-scan base-package=\"$L\"/>}\nin {@code $L}\n",
                fqcn,
                basePackage,
                xmlSources);

        // Add checked exceptions from the constructor (or throws Exception for reflection)
        addExceptionsFromConstructor(methodBuilder, constructor, needsReflection);

        if (constructor != null && constructor.getParameterCount() > 0) {
            addConstructorParameters(methodBuilder, constructor);
        }

        if (needsReflection) {
            generateReflectionConstructorCall(methodBuilder, constructor, returnType);
        } else if (constructor == null || constructor.getParameterCount() == 0) {
            methodBuilder.addStatement("return new $T()", returnType);
        } else {
            methodBuilder.addStatement("return new $T($L)", returnType, buildParamNames(constructor));
        }

        context.printMessage(NOTE, "Generated @Bean method for component: %s (%s)".formatted(beanName, fqcn));
        return methodBuilder.build();
    }

    /**
     * Resolve the constructor to use for bean instantiation, following Spring conventions:
     *
     * <ol>
     *   <li>Explicit {@code @Autowired} constructor (wins even with multiple constructors)
     *   <li>No-arg constructor
     *   <li>Single-constructor autowiring (the only declared constructor with parameters)
     * </ol>
     */
    private @Nullable Constructor<?> resolveConstructor(Class<?> beanClass) {
        // 1. Look for @Autowired-annotated constructor
        for (Constructor<?> ctor : beanClass.getDeclaredConstructors()) {
            if (ctor.isAnnotationPresent(org.springframework.beans.factory.annotation.Autowired.class)) {
                return ctor;
            }
        }
        // 2. Try no-arg constructor
        try {
            return beanClass.getDeclaredConstructor();
        } catch (NoSuchMethodException _) {
            // 3. Single-constructor autowiring
            return Reflections.resolveAutowiredConstructor(beanClass);
        }
    }

    private void addConstructorParameters(MethodSpec.Builder methodBuilder, Constructor<?> constructor) {
        java.lang.reflect.Parameter[] params = constructor.getParameters();
        for (java.lang.reflect.Parameter param : params) {
            String paramName = generateParameterName(param.getType());

            com.palantir.javapoet.ParameterSpec.Builder paramBuilder = com.palantir.javapoet.ParameterSpec.builder(
                    Reflections.classToClassName(param.getType()), paramName);

            // Propagate @Qualifier annotation from constructor parameter
            org.springframework.beans.factory.annotation.Qualifier qualifier =
                    param.getAnnotation(org.springframework.beans.factory.annotation.Qualifier.class);
            if (qualifier != null) {
                paramBuilder.addAnnotation(
                        AnnotationSpec.builder(org.springframework.beans.factory.annotation.Qualifier.class)
                                .addMember("value", "$S", qualifier.value())
                                .build());
            }

            methodBuilder.addParameter(paramBuilder.build());
        }
    }

    private String buildParamNames(Constructor<?> constructor) {
        Class<?>[] paramTypes = constructor.getParameterTypes();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < paramTypes.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(generateParameterName(paramTypes[i]));
        }
        return sb.toString();
    }

    private String generateParameterName(Class<?> paramType) {
        return Introspector.decapitalize(paramType.getSimpleName());
    }

    /**
     * Add checked exceptions from the constructor to the method signature. For non-public constructors using
     * reflection, adds {@code throws Exception} instead of the specific exception types. Mirrors
     * {@link AbstractBeanMethodGenerator#addExceptionsFromConstructor}.
     */
    private void addExceptionsFromConstructor(
            MethodSpec.Builder methodBuilder, @Nullable Constructor<?> constructor, boolean reflectionBased) {
        if (constructor == null) {
            return;
        }
        java.util.stream.Stream<Class<?>> exceptionTypes;
        if (reflectionBased) {
            exceptionTypes = java.util.stream.Stream.of(Exception.class);
        } else {
            exceptionTypes = java.util.stream.Stream.of(constructor.getExceptionTypes());
        }
        exceptionTypes
                .filter(e -> Exception.class.isAssignableFrom(e) && !RuntimeException.class.isAssignableFrom(e))
                .map(ClassName::get)
                .forEach(methodBuilder::addException);
    }

    private void generateReflectionConstructorCall(
            MethodSpec.Builder methodBuilder, Constructor<?> constructor, ClassName returnType) {

        Class<?>[] paramTypes = constructor.getParameterTypes();

        // Build parameter types for getDeclaredConstructor
        StringBuilder paramTypeClasses = new StringBuilder();
        StringBuilder paramValues = new StringBuilder();
        for (int i = 0; i < paramTypes.length; i++) {
            if (i > 0) {
                paramTypeClasses.append(", ");
                paramValues.append(", ");
            }
            paramTypeClasses.append(Reflections.classToClassName(paramTypes[i])).append(".class");
            paramValues.append(generateParameterName(paramTypes[i]));
        }

        methodBuilder.addStatement(
                "java.lang.reflect.Constructor<?> constructor = $T.class.getDeclaredConstructor($L)",
                returnType,
                paramTypeClasses.toString());
        methodBuilder.addStatement("constructor.setAccessible(true)");
        methodBuilder.addStatement("return ($T) constructor.newInstance($L)", returnType, paramValues.toString());
    }
}
