/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.spring.config.transpiler.generator;

import static org.geoserver.spring.config.transpiler.xml.EnhancedBeanDefinition.sanitizeBeanName;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.MethodSpec;
import java.util.ArrayList;
import java.util.List;
import org.geoserver.spring.config.transpiler.context.BeanGenerationContext;
import org.geoserver.spring.config.transpiler.context.TranspilationContext;
import org.springframework.aop.framework.ProxyFactoryBean;
import org.springframework.beans.PropertyValue;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.config.RuntimeBeanReference;
import org.springframework.beans.factory.config.TypedStringValue;
import org.springframework.beans.factory.support.ManagedList;

/**
 * Generator for generating {@code @Bean} methods for Spring AOP {@link ProxyFactoryBean} definitions.
 *
 * <p>Spring's {@code ProxyFactoryBean} is a specialized factory bean that creates AOP proxies programmatically. It
 * requires specific handling of properties that don't follow standard bean property patterns:
 *
 * <ul>
 *   <li><strong>proxyInterfaces:</strong> String class names must be converted to {@code Class<?>[]} array
 *   <li><strong>interceptorNames:</strong> List of strings must be converted to {@code String[]} array
 *   <li><strong>target/targetName:</strong> Reference to the actual object being proxied
 * </ul>
 *
 * <h2>Spring XML Pattern</h2>
 *
 * <pre>{@code
 * <bean id="wcs100Service" class="org.springframework.aop.framework.ProxyFactoryBean">
 *     <property name="proxyInterfaces">
 *         <value>org.geoserver.wcs.WebCoverageService100</value>
 *     </property>
 *     <property name="interceptorNames">
 *         <list>
 *             <value>wcs100Logger</value>
 *             <value>wcs100ServiceInterceptor*</value>
 *             <value>wcs100ServiceTarget</value>
 *         </list>
 *     </property>
 * </bean>
 * }</pre>
 *
 * <h2>Generated Java Output</h2>
 *
 * <pre>{@code
 * @Bean
 * org.springframework.aop.framework.ProxyFactoryBean wcs100Service() {
 *     org.springframework.aop.framework.ProxyFactoryBean bean = new org.springframework.aop.framework.ProxyFactoryBean();
 *     bean.setProxyInterfaces(new Class<?>[] { org.geoserver.wcs.WebCoverageService100.class });
 *     bean.setInterceptorNames(new String[] { "wcs100Logger", "wcs100ServiceInterceptor*", "wcs100ServiceTarget" });
 *     return bean;
 * }
 * }</pre>
 *
 * <h2>AOP Proxy Concepts</h2>
 *
 * <p>The {@code ProxyFactoryBean} creates dynamic proxies that wrap target objects with:
 *
 * <ul>
 *   <li><strong>Interceptors:</strong> Method interceptors that implement cross-cutting concerns
 *   <li><strong>Advisors:</strong> Combination of advice and pointcuts
 *   <li><strong>Target:</strong> The actual object being proxied
 *   <li><strong>Interfaces:</strong> The interfaces the proxy should implement
 * </ul>
 *
 * <p>This generator handles the transformation from XML property syntax to the correct Java API calls required by
 * {@code ProxyFactoryBean}.
 *
 * @since 3.0.0
 * @see org.springframework.aop.framework.ProxyFactoryBean
 * @see SimpleBeanMethodGenerator
 */
@SuppressWarnings("java:S1192")
public class ProxyFactoryBeanMethodGenerator extends AbstractBeanMethodGenerator {

    private static final String PROXY_FACTORY_BEAN_CLASS = "org.springframework.aop.framework.ProxyFactoryBean";

    @Override
    public boolean canHandle(BeanDefinition beanDefinition) {
        return PROXY_FACTORY_BEAN_CLASS.equals(beanDefinition.getBeanClassName());
    }

    @Override
    public int getPriority() {
        return 40; // Higher priority than SimpleBeanMethodGenerator (200) to handle ProxyFactoryBean specifically
    }

    @Override
    public MethodSpec generateBeanMethod(BeanGenerationContext beanContext) {
        TranspilationContext transpilationContext = beanContext.getTranspilationContext();
        BeanDefinition beanDefinition = beanContext.getBeanDefinition();
        String beanName = beanContext.getBeanName();

        // Sanitize bean name for method name
        String methodName = sanitizeBeanName(beanName);

        // For auto-generated bean names, add unique suffix to avoid collisions
        if (beanContext.isAutoGenerated()) {
            String uniqueSuffix = transpilationContext.getUniqueMethodSuffix();
            methodName = methodName + "_" + uniqueSuffix;
        }

        // ProxyFactoryBean return type
        ClassName returnType = ClassName.get("org.springframework.aop.framework", "ProxyFactoryBean");

        // Create method builder
        MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(methodName)
                .addModifiers() // Package-private
                .returns(returnType)
                .addException(ClassNotFoundException.class); // ProxyFactoryBean.setProxyInterfaces() throws it

        // Add {@code @Bean} annotation
        methodBuilder.addAnnotation(createBeanAnnotation(beanContext));

        // Add javadoc using enhanced bean info
        String javadocContent = beanContext.generateJavadoc();
        methodBuilder.addJavadoc(javadocContent);

        // Generate method body
        generateProxyFactoryBeanMethodBody(methodBuilder, beanDefinition);

        return methodBuilder.build();
    }

    /** Generate the method body for ProxyFactoryBean with specialized property handling. */
    private void generateProxyFactoryBeanMethodBody(MethodSpec.Builder methodBuilder, BeanDefinition beanDefinition) {
        // Create the ProxyFactoryBean instance
        ClassName proxyFactoryBeanClass = ClassName.get("org.springframework.aop.framework", "ProxyFactoryBean");
        methodBuilder.addStatement("$T bean = new $T()", proxyFactoryBeanClass, proxyFactoryBeanClass);

        // Process each property with specialized handling
        if (beanDefinition.hasPropertyValues()) {
            for (PropertyValue pv : beanDefinition.getPropertyValues().getPropertyValues()) {
                String propertyName = pv.getName();
                Object value = pv.getValue();

                switch (propertyName) {
                    case "proxyInterfaces":
                        generateProxyInterfacesSetter(methodBuilder, value);
                        break;
                    case "interceptorNames": {
                        if (value instanceof ManagedList<?> managedList) {
                            generateInterceptorNamesSetter(methodBuilder, managedList);
                        } else {
                            throw new IllegalArgumentException("Expected ManagedList, got " + value);
                        }
                        break;
                    }
                    case "target", "targetName":
                        generateTargetSetter(methodBuilder, propertyName, value);
                        break;
                    default:
                        throw new UnsupportedOperationException("Should generate a standard setter here?");
                }
            }
        }

        methodBuilder.addStatement("return bean");
    }

    /** Generate setter for proxyInterfaces property - converts string class names to Class<?>[]. */
    private void generateProxyInterfacesSetter(MethodSpec.Builder methodBuilder, Object value) {
        if (value instanceof TypedStringValue stringValue1) {
            // Single interface
            String interfaceClassName = stringValue1.getValue();
            methodBuilder.addStatement("bean.setProxyInterfaces(new Class<?>[] { $L.class })", interfaceClassName);
        } else if (value instanceof ManagedList<?> managedList) {
            List<String> interfaceNames = new ArrayList<>();

            for (Object item : managedList) {
                if (item instanceof TypedStringValue stringValue) {
                    interfaceNames.add(stringValue.getValue());
                }
            }

            if (interfaceNames.size() == 1) {
                methodBuilder.addStatement(
                        "bean.setProxyInterfaces(new Class<?>[] { $L.class })", interfaceNames.get(0));
            } else if (interfaceNames.size() > 1) {
                CodeBlock codeBlock = generateArrayWithMultipleInterfaces(interfaceNames);
                methodBuilder.addStatement("bean.setProxyInterfaces($L)", codeBlock);
            }
        }
    }

    private CodeBlock generateArrayWithMultipleInterfaces(List<String> interfaceNames) {
        CodeBlock.Builder arrayBuilder = CodeBlock.builder().add("new Class<?>[] { ");
        for (int i = 0; i < interfaceNames.size(); i++) {
            if (i > 0) {
                arrayBuilder.add(", ");
            }
            arrayBuilder.add("$L.class", interfaceNames.get(i));
        }
        arrayBuilder.add(" }");
        return arrayBuilder.build();
    }

    /** Generate setter for interceptorNames property - converts List<String> to String[]. */
    private void generateInterceptorNamesSetter(MethodSpec.Builder methodBuilder, ManagedList<?> managedList) {
        List<String> interceptorNames = new ArrayList<>();

        for (Object item : managedList) {
            if (item instanceof TypedStringValue stringValue) {
                interceptorNames.add(stringValue.getValue());
            }
        }

        if (interceptorNames.size() == 1) {
            methodBuilder.addStatement("bean.setInterceptorNames(new String[] { $S })", interceptorNames.get(0));
        } else if (interceptorNames.size() > 1) {
            CodeBlock codeBlock = generateArrayWithMultipleInterceptorNames(interceptorNames);
            methodBuilder.addStatement("bean.setInterceptorNames($L)", codeBlock);
        }
    }

    private CodeBlock generateArrayWithMultipleInterceptorNames(List<String> interceptorNames) {
        CodeBlock.Builder arrayBuilder = CodeBlock.builder().add("new String[] { ");
        for (int i = 0; i < interceptorNames.size(); i++) {
            if (i > 0) {
                arrayBuilder.add(", ");
            }
            arrayBuilder.add("$S", interceptorNames.get(i));
        }
        arrayBuilder.add(" }");
        return arrayBuilder.build();
    }

    /** Generate setter for target/targetName properties. */
    private void generateTargetSetter(MethodSpec.Builder methodBuilder, String propertyName, Object value) {
        // Convert property name to setter method name
        String setterName = Reflections.buildSetterName(propertyName);

        if (value instanceof RuntimeBeanReference beanRef) {
            methodBuilder.addComment("TODO: Add method parameter for bean reference: " + beanRef.getBeanName());
            methodBuilder.addStatement(
                    "// bean.$L($L); // Bean reference: $L",
                    setterName,
                    sanitizeBeanName(beanRef.getBeanName()),
                    beanRef.getBeanName());
        } else if (value instanceof TypedStringValue typedString) {
            String stringValue = typedString.getValue();
            methodBuilder.addStatement("bean.$L($S)", setterName, stringValue);
        }
    }
}
