info:
  component: ${spring.application.name}
  instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${spring.cloud.client.ip-address}}:${server.port}}

server:
  port: 8080
  # Ensures protocol (http vs https) is preserved behind K8s Ingress or Docker Proxies
  forward-headers-strategy: framework
  shutdown: graceful

management:
  # enable custom properties in /actuator/info like info.component
  info.env.enabled: true
  server.port: 8081
  
geoserver:
  metrics:
    enabled: true
    instance-id: ${info.instance-id}

spring:
  config.location: optional:${geoserver.config.location:file:/etc/geoserver/}
  main:
    banner-mode: off
    # Required for GeoServer initialization
    allow-bean-definition-overriding: true
    allow-circular-references: true
  integration:
    jdbc:
      # Prevents circular dependency between GeoServer's PGConfig and Spring Integration.
      # Setting this to 'never' stops the creation of 'integrationDataSourceInitializer',
      # allowing IntegrationAutoConfiguration to run (fixing the Bus NPE) without
      # trying to manage database schemas.
      initialize-schema: never
  jmx.enabled: false
  # EXCLUSIONS (Removed unnecessary auto-configs for performance or because they cause an initialization error)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
