# Builds and pushes docker images on main and tags

name: Build on any branch
on:
  push:
    branches:
      - '**'
      - "!main"
    paths:
      - "Makefile"
      - "pom.xml"
      - ".github/workflows/build.yaml"
      - "config"
      - "src/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Install CI dependencies
      run: python3 -m pip install --user --requirement=ci/requirements.txt

    - name: Validate source code formatting
      run: make lint

    - name: Build and test
      run: |
        make install test

    - name: Build docker images
      run: |
        make build-image

    - name: Run acceptance tests
      run: |
        make acceptance-tests

    - name: Print docker compose logs
      run: (cd docker && c2cciutils-docker-logs)
      if: always()

    - name: Remove project jars from cached repository
      run: |
        rm -rf ~/.m2/repository/org/geoserver
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
