# Builds and pushes docker images on main and tags

name: Build on any branch
on:
  push:
    branches:
      - "feature/**"
      - "bug/**"
      - "build/**"
    paths:
      - "Makefile"
      - "pom.xml"
      - ".github/workflows/build.yaml"
      - "config"
      - "src/**"
      - "acceptance_tests/**"
      - "ci/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Validate source code formatting
      run: make lint

    - name: Build and test
      run: |
        make install test

    - name: Build docker images
      run: |
        make build-image

    - name: Remove project jars from cached repository
      run: |
        rm -rf ~/.m2/repository/org/geoserver
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
